org: polomaru
service: api-web-scraping

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  environment:
    TABLE_NAME: TareaWebScrapping
    AWS_REGION: us-east-1
  iam:
    role: arn:aws:iam::157403467473:role/LabRole
  layers:
    - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:15

functions:
  scrape_table:
    handler: scrap_table.handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true

resources:
  Resources:
    TareaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TareaWebScrapping
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST