org: polomaru
service: api-web-scraping
provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  environment:
    TABLE_NAME: TareaWebScrapping

functions:
  scrape_table:
    handler: scrap.handler     # archivo scrap.js → module.exports.handler
    package:
      include:
        - scrap.js
    events:
      - http:
          path: scrape/table
          method: get
          cors: true

resources:
  Resources:
    TareaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TareaWebScrapping
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

layers:
  chromeLambda:
    path: chrome-aws-lambda-layer-package # si usas un layer empaquetado con chrome-aws-lambda
    compatibleRuntimes:
      - nodejs18.x
