org: polomaru
service: api-web-scraping

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 28
  environment:
    TABLE_NAME: TareaWebScrapping
  iam:
    role: arn:aws:iam::157403467473:role/LabRole
layers:
  chromeAwsLambda:
    arn: arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:24
functions:
  scrape_table:
    handler: scrap.handler   # scrap.js → module.exports.handler
    events:
      - http:
          path: scrape/table
          method: get
          cors: true

resources:
  Resources:
    TareaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TareaWebScrapping
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
